//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesApp.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructions
    {
        public int InstructionID { get; set; }
        public int RecipeID { get; set; }
        public string InstructionText { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
