//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesApp.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.CategoryRecipe = new HashSet<CategoryRecipe>();
            this.CommentsRecipe = new HashSet<CommentsRecipe>();
            this.IngredientsRecipe = new HashSet<IngredientsRecipe>();
            this.SubcategoryRecipe = new HashSet<SubcategoryRecipe>();
            this.Instructions = new HashSet<Instructions>();
        }
    
        public int RecipeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PictureLocation { get; set; }
        public int RatingID { get; set; }
        public int PrepTime { get; set; }
        public int CookTime { get; set; }
        public string LongDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryRecipe> CategoryRecipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentsRecipe> CommentsRecipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsRecipe> IngredientsRecipe { get; set; }
        public virtual Ratings Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubcategoryRecipe> SubcategoryRecipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instructions> Instructions { get; set; }
    }
}
